/**
 * DoodleNet(Quick, Draw! 345종) 출력 순서 그대로의 [영문 클래스, 한국어 이름] 표.
 * 순서가 모델 출력 인덱스와 1:1로 대응하므로 절대 정렬하거나 중간에 끼워 넣지 말 것
 * (public/models/doodlenet/ — ml5-data-and-models의 class_names.txt와 같은 순서)
 */
export const DOODLE_CLASSES: readonly (readonly [id: string, ko: string])[] = [
  ['flashlight', '손전등'], ['belt', '벨트'], ['mushroom', '버섯'], ['pond', '연못'], ['strawberry', '딸기'],
  ['pineapple', '파인애플'], ['sun', '해'], ['cow', '소'], ['ear', '귀'], ['bush', '덤불'],
  ['pliers', '펜치'], ['watermelon', '수박'], ['apple', '사과'], ['baseball', '야구공'], ['feather', '깃털'],
  ['shoe', '신발'], ['leaf', '나뭇잎'], ['lollipop', '막대사탕'], ['crown', '왕관'], ['ocean', '바다'],
  ['horse', '말'], ['mountain', '산'], ['mosquito', '모기'], ['mug', '머그컵'], ['hospital', '병원'],
  ['saw', '톱'], ['castle', '성'], ['angel', '천사'], ['underwear', '속옷'], ['traffic_light', '신호등'],
  ['cruise_ship', '유람선'], ['marker', '마커펜'], ['blueberry', '블루베리'], ['flamingo', '플라밍고'], ['face', '얼굴'],
  ['hockey_stick', '하키채'], ['bucket', '양동이'], ['campfire', '모닥불'], ['asparagus', '아스파라거스'], ['skateboard', '스케이트보드'],
  ['door', '문'], ['suitcase', '여행가방'], ['skull', '해골'], ['cloud', '구름'], ['paint_can', '페인트통'],
  ['hockey_puck', '하키 퍽'], ['steak', '스테이크'], ['house_plant', '화분'], ['sleeping_bag', '침낭'], ['bench', '벤치'],
  ['snowman', '눈사람'], ['arm', '팔'], ['crayon', '크레파스'], ['fan', '선풍기'], ['shovel', '삽'],
  ['leg', '다리'], ['washing_machine', '세탁기'], ['harp', '하프'], ['toothbrush', '칫솔'], ['tree', '나무'],
  ['bear', '곰'], ['rake', '갈퀴'], ['megaphone', '확성기'], ['knee', '무릎'], ['guitar', '기타'],
  ['calculator', '계산기'], ['hurricane', '태풍'], ['grapes', '포도'], ['paintbrush', '붓'], ['couch', '소파'],
  ['nose', '코'], ['square', '네모'], ['wristwatch', '손목시계'], ['penguin', '펭귄'], ['bridge', '다리(건축물)'],
  ['octagon', '팔각형'], ['submarine', '잠수함'], ['screwdriver', '드라이버'], ['rollerskates', '롤러스케이트'], ['ladder', '사다리'],
  ['wine_bottle', '와인병'], ['cake', '케이크'], ['bracelet', '팔찌'], ['broom', '빗자루'], ['yoga', '요가'],
  ['finger', '손가락'], ['fish', '물고기'], ['line', '선'], ['truck', '트럭'], ['snake', '뱀'],
  ['bus', '버스'], ['stitches', '바느질 자국'], ['snorkel', '스노클'], ['shorts', '반바지'], ['bowtie', '나비넥타이'],
  ['pickup_truck', '픽업트럭'], ['tooth', '이빨'], ['snail', '달팽이'], ['foot', '발'], ['crab', '게'],
  ['school_bus', '스쿨버스'], ['train', '기차'], ['dresser', '서랍장'], ['sock', '양말'], ['tractor', '트랙터'],
  ['map', '지도'], ['hedgehog', '고슴도치'], ['coffee_cup', '커피잔'], ['computer', '컴퓨터'], ['matches', '성냥'],
  ['beard', '턱수염'], ['frog', '개구리'], ['crocodile', '악어'], ['bathtub', '욕조'], ['rain', '비'],
  ['moon', '달'], ['bee', '벌'], ['knife', '칼'], ['boomerang', '부메랑'], ['lighthouse', '등대'],
  ['chandelier', '샹들리에'], ['jail', '감옥'], ['pool', '수영장'], ['stethoscope', '청진기'], ['frying_pan', '프라이팬'],
  ['cell_phone', '휴대폰'], ['binoculars', '쌍안경'], ['purse', '지갑'], ['lantern', '랜턴'], ['birthday_cake', '생일 케이크'],
  ['clarinet', '클라리넷'], ['palm_tree', '야자수'], ['aircraft_carrier', '항공모함'], ['vase', '꽃병'], ['eraser', '지우개'],
  ['shark', '상어'], ['skyscraper', '고층 빌딩'], ['bicycle', '자전거'], ['sink', '세면대'], ['teapot', '찻주전자'],
  ['circle', '동그라미'], ['tornado', '회오리바람'], ['bird', '새'], ['stereo', '오디오'], ['mouth', '입'],
  ['key', '열쇠'], ['hot_dog', '핫도그'], ['spoon', '숟가락'], ['laptop', '노트북'], ['cup', '컵'],
  ['bottlecap', '병뚜껑'], ['The_Great_Wall_of_China', '만리장성'], ['The_Mona_Lisa', '모나리자'], ['smiley_face', '웃는 얼굴'], ['waterslide', '워터슬라이드'],
  ['eyeglasses', '안경'], ['ceiling_fan', '천장 선풍기'], ['lobster', '랍스터'], ['moustache', '콧수염'], ['carrot', '당근'],
  ['garden', '정원'], ['police_car', '경찰차'], ['postcard', '엽서'], ['necklace', '목걸이'], ['helmet', '헬멧'],
  ['blackberry', '블랙베리'], ['beach', '해변'], ['golf_club', '골프채'], ['car', '자동차'], ['panda', '판다'],
  ['alarm_clock', '자명종'], ['t-shirt', '티셔츠'], ['dog', '강아지'], ['bread', '빵'], ['wine_glass', '와인잔'],
  ['lighter', '라이터'], ['flower', '꽃'], ['bandage', '반창고'], ['drill', '드릴'], ['butterfly', '나비'],
  ['swan', '백조'], ['owl', '부엉이'], ['raccoon', '너구리'], ['squiggle', '구불구불한 선'], ['calendar', '달력'],
  ['giraffe', '기린'], ['elephant', '코끼리'], ['trumpet', '트럼펫'], ['rabbit', '토끼'], ['trombone', '트롬본'],
  ['sheep', '양'], ['onion', '양파'], ['church', '교회'], ['flip_flops', '쪼리'], ['spreadsheet', '스프레드시트'],
  ['pear', '배'], ['clock', '시계'], ['roller_coaster', '롤러코스터'], ['parachute', '낙하산'], ['kangaroo', '캥거루'],
  ['duck', '오리'], ['remote_control', '리모컨'], ['compass', '나침반'], ['monkey', '원숭이'], ['rainbow', '무지개'],
  ['tennis_racquet', '테니스 라켓'], ['lion', '사자'], ['pencil', '연필'], ['string_bean', '껍질콩'], ['oven', '오븐'],
  ['star', '별'], ['cat', '고양이'], ['pizza', '피자'], ['soccer_ball', '축구공'], ['syringe', '주사기'],
  ['flying_saucer', 'UFO'], ['eye', '눈(신체)'], ['cookie', '쿠키'], ['floor_lamp', '스탠드 조명'], ['mouse', '쥐'],
  ['toilet', '변기'], ['toaster', '토스터'], ['The_Eiffel_Tower', '에펠탑'], ['airplane', '비행기'], ['stove', '가스레인지'],
  ['cello', '첼로'], ['stop_sign', '정지 표지판'], ['tent', '텐트'], ['diving_board', '다이빙대'], ['light_bulb', '전구'],
  ['hammer', '망치'], ['scorpion', '전갈'], ['headphones', '헤드폰'], ['basket', '바구니'], ['spider', '거미'],
  ['paper_clip', '클립'], ['sweater', '스웨터'], ['ice_cream', '아이스크림'], ['envelope', '편지봉투'], ['sea_turtle', '바다거북'],
  ['donut', '도넛'], ['hat', '모자'], ['hourglass', '모래시계'], ['broccoli', '브로콜리'], ['jacket', '재킷'],
  ['backpack', '배낭'], ['book', '책'], ['lightning', '번개'], ['drums', '드럼'], ['snowflake', '눈송이'],
  ['radio', '라디오'], ['banana', '바나나'], ['camel', '낙타'], ['canoe', '카누'], ['toothpaste', '치약'],
  ['chair', '의자'], ['picture_frame', '액자'], ['parrot', '앵무새'], ['sandwich', '샌드위치'], ['lipstick', '립스틱'],
  ['pants', '바지'], ['violin', '바이올린'], ['brain', '뇌'], ['power_outlet', '콘센트'], ['triangle', '세모'],
  ['hamburger', '햄버거'], ['dragon', '용'], ['bulldozer', '불도저'], ['cannon', '대포'], ['dolphin', '돌고래'],
  ['zebra', '얼룩말'], ['animal_migration', '동물 대이동'], ['camouflage', '위장무늬'], ['scissors', '가위'], ['basketball', '농구공'],
  ['elbow', '팔꿈치'], ['umbrella', '우산'], ['windmill', '풍차'], ['table', '탁자'], ['rifle', '소총'],
  ['hexagon', '육각형'], ['potato', '감자'], ['anvil', '모루'], ['sword', '칼(검)'], ['peanut', '땅콩'],
  ['axe', '도끼'], ['television', '텔레비전'], ['rhinoceros', '코뿔소'], ['baseball_bat', '야구 방망이'], ['speedboat', '모터보트'],
  ['sailboat', '돛단배'], ['zigzag', '지그재그'], ['garden_hose', '정원 호스'], ['river', '강'], ['house', '집'],
  ['pillow', '베개'], ['ant', '개미'], ['tiger', '호랑이'], ['stairs', '계단'], ['cooler', '아이스박스'],
  ['see_saw', '시소'], ['piano', '피아노'], ['fireplace', '벽난로'], ['popsicle', '아이스바'], ['dumbbell', '아령'],
  ['mailbox', '우체통'], ['barn', '헛간'], ['hot_tub', '온수 욕조'], ['teddy-bear', '곰인형'], ['fork', '포크'],
  ['dishwasher', '식기세척기'], ['peas', '완두콩'], ['hot_air_balloon', '열기구'], ['keyboard', '키보드'], ['microwave', '전자레인지'],
  ['wheel', '바퀴'], ['fire_hydrant', '소화전'], ['van', '승합차'], ['camera', '카메라'], ['whale', '고래'],
  ['candle', '양초'], ['octopus', '문어'], ['pig', '돼지'], ['swing_set', '그네'], ['helicopter', '헬리콥터'],
  ['saxophone', '색소폰'], ['passport', '여권'], ['bat', '박쥐'], ['ambulance', '구급차'], ['diamond', '다이아몬드'],
  ['goatee', '염소수염'], ['fence', '울타리'], ['grass', '풀'], ['mermaid', '인어'], ['motorbike', '오토바이'],
  ['microphone', '마이크'], ['toe', '발가락'], ['cactus', '선인장'], ['nail', '못'], ['telephone', '전화기'],
  ['hand', '손'], ['squirrel', '다람쥐'], ['streetlight', '가로등'], ['bed', '침대'], ['firetruck', '소방차'],
]

/** 추측 후보로는 보여주되 제시어로는 내지 않는 클래스 — 도형·선처럼 너무 쉽거나, 그림으로 나타내기 애매하거나,
 *  비슷한 다른 클래스와 헷갈려서 정답을 그려도 억울하게 틀리기 쉬운 것들 */
const EXCLUDED_FROM_PROMPTS = new Set([
  'line', 'squiggle', 'zigzag', 'circle', 'square', 'triangle', 'hexagon', 'octagon',
  'animal_migration', 'camouflage', 'stitches', 'spreadsheet', 'yoga', 'bush', 'garden', 'string_bean',
  'goatee', 'hockey_puck', 'marker', 'hot_tub', 'pickup_truck', 'coffee_cup', 'mug', 'cooler', 'pond',
])

/** 제시어로 낼 수 있는 클래스의 모델 출력 인덱스 목록 */
export const DOODLE_PROMPT_INDICES: readonly number[] = DOODLE_CLASSES.flatMap(([id], i) =>
  EXCLUDED_FROM_PROMPTS.has(id) ? [] : [i],
)
